// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import GraphController from "./graph_controller"
application.register("graph", GraphController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import PdfModalController from "./pdf_modal_controller"
application.register("pdf-modal", PdfModalController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)
